/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package topn;

import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

    @Test
    void testTopN() {
        int n = 3;

        Library classUnderTest = new Library();

        List<Integer> list = classUnderTest.topN(Stream.of(1, 6, 5, 3, 9, 6, 11), n);
        assertEquals(n, list.size());
        assertTrue(list.containsAll(List.of(11, 9, 6)));
        assertEquals(11, list.get(0));

        list.forEach(System.out::println);
    }

    @Test
    void testTopNLoad() {
        int limit = 100_000_000;
        int n = 10;

        Library classUnderTest = new Library();

        List<Integer> list = classUnderTest.topN(Stream.iterate(0, value -> value + 1).limit(limit), n);
        assertEquals(n, list.size());
        assertEquals(limit - 1, list.get(0));
        assertEquals(limit - 2, list.get(1));

        list.forEach(System.out::println);
    }
}
